"""The press — member-contributed content, attributed and closed-loop.

A1 of the agents-expansion plan (docs/agents-expansion-plan.md): the
contribution spine. Members publish material into the app under a stated
license; every contribution is scrubbed, genre-keyed, author-attributed,
durable, and revocable-forward. Later phases build on exactly these
records: the newsroom composes them into stories (A2) and the ad
dividend splits over their attribution weights (A5). The poll floor
(A3) has been REMOVED — the member's pairwise preference book it wrote
into survives in :mod:`pairwise`, fed by story feedback and future
survey instruments.

The package is closed-loop by law (plan invariant 1): nothing in here
reaches a web-search or external-content seam — pinned by the import
scan in ``tests/test_press.py``.
"""

from .composer import (
    COMPOSER_VERSION,
    compose_post,
    compose_story_parts,
    desk_post,
    lineage_from,
    source_rows,
    sources_summary,
)
from .contributions import (
    LICENSES,
    MAX_BODY_CHARS,
    MAX_MEDIA,
    MAX_TITLE_CHARS,
    SIMILARITY_FLAG,
    ContentContribution,
    ContributionStore,
    MediaRef,
    PressDesk,
    PressError,
    leak_report,
)
from .demand import (
    DEMAND_READER_FLOOR,
    DEMAND_VERSION,
    GenreDemand,
    GenreDemandStore,
    GenreEvidence,
    demand_line,
    rank_demand,
)
from .editions import (
    EDITION_LABEL,
    EDITION_PULSE_GOAL,
    EDITION_SIZE,
    MATCH_FLOOR,
    PreferenceStore,
    edition_message,
    match_edition,
    rank_edition,
)
from .intake import (
    DROPPED,
    GATHER_ASK,
    GATHER_ASK_WORDS,
    INTAKE_LICENSE,
    IntakeDraft,
    IntakeStore,
    draft_from_material,
    fold_answer,
    looks_like_material,
    review,
)
from .metrics import METRICS_K_FLOOR, StoryMetricsStore
from .newsroom import LineageShare, Newsroom, Story, StoryStore
from .pairwise import PairwiseStore
from .personalize import (
    SEMANTIC_PULL,
    Taste,
    semantic_affinity,
    taste_snippet,
)
from .rewards import (
    REWARDS_VERSION,
    TRANCHE_LINEAGE,
    TRANCHE_RESEARCH,
    TRANCHE_SURVEY,
    RewardCitationStore,
    SourceShare,
    merged_shares,
    source_split,
)
from .standards import RUBRIC_VERSION, RubricBreakdown, score, select
from .surveys import (
    SURVEY_K_FLOOR,
    SURVEY_SAMPLE_SIZE,
    SURVEY_TTL_HOURS,
    SURVEY_VERSION,
    Survey,
    SurveyDesk,
    SurveyOption,
    SurveyStore,
    compose_survey,
    draw_sample,
)
from .taxonomy import GENRES, TAXONOMY_VERSION, Genre, taxonomy_items
from .topics import (
    TOPIC_VERSION,
    TOPICS_PER_RUN,
    BeatRow,
    ClusterPiece,
    MarketFact,
    TopicBrief,
    TopicBriefStore,
    TopicCandidate,
    mine_clusters,
    mine_measured_gaps,
    mine_price_moves,
    mine_trust_bands,
    select_topics,
    topics_line,
)

__all__ = [
    "COMPOSER_VERSION",
    "DEMAND_READER_FLOOR",
    "DEMAND_VERSION",
    "DROPPED",
    "EDITION_LABEL",
    "EDITION_PULSE_GOAL",
    "EDITION_SIZE",
    "GATHER_ASK",
    "GATHER_ASK_WORDS",
    "GENRES",
    "GenreDemand",
    "GenreDemandStore",
    "GenreEvidence",
    "INTAKE_LICENSE",
    "LICENSES",
    "MAX_BODY_CHARS",
    "MAX_MEDIA",
    "MATCH_FLOOR",
    "MAX_TITLE_CHARS",
    "METRICS_K_FLOOR",
    "REWARDS_VERSION",
    "RUBRIC_VERSION",
    "SEMANTIC_PULL",
    "SIMILARITY_FLAG",
    "SURVEY_K_FLOOR",
    "SURVEY_SAMPLE_SIZE",
    "SURVEY_TTL_HOURS",
    "SURVEY_VERSION",
    "TAXONOMY_VERSION",
    "TOPIC_VERSION",
    "TOPICS_PER_RUN",
    "TRANCHE_LINEAGE",
    "TRANCHE_RESEARCH",
    "TRANCHE_SURVEY",
    "Taste",
    "BeatRow",
    "ClusterPiece",
    "ContentContribution",
    "ContributionStore",
    "Genre",
    "IntakeDraft",
    "IntakeStore",
    "LineageShare",
    "MarketFact",
    "MediaRef",
    "Newsroom",
    "PairwiseStore",
    "PreferenceStore",
    "PressDesk",
    "PressError",
    "RewardCitationStore",
    "RubricBreakdown",
    "SourceShare",
    "Story",
    "StoryMetricsStore",
    "StoryStore",
    "Survey",
    "SurveyDesk",
    "SurveyOption",
    "SurveyStore",
    "TopicBrief",
    "TopicBriefStore",
    "TopicCandidate",
    "compose_post",
    "compose_story_parts",
    "compose_survey",
    "demand_line",
    "desk_post",
    "draft_from_material",
    "draw_sample",
    "edition_message",
    "fold_answer",
    "rank_demand",
    "leak_report",
    "lineage_from",
    "looks_like_material",
    "match_edition",
    "merged_shares",
    "mine_clusters",
    "mine_measured_gaps",
    "mine_price_moves",
    "mine_trust_bands",
    "rank_edition",
    "review",
    "score",
    "select",
    "select_topics",
    "source_rows",
    "source_split",
    "sources_summary",
    "semantic_affinity",
    "taste_snippet",
    "taxonomy_items",
    "topics_line",
]
